### ISSUE TITLE
Use GIT_ROOT_DIR var in Dockerfiles

### ISSUE THREAD

**Issue by gpsaggese** [alphamatic/amp#1771]
Unfortunately docker files need to refer to other files using relative paths, which is difficult to read and brittle.

```
    volumes:
      - ../../../:/app
      - ~/.aws:/app/home/.aws
    env_file:
      - ../env/local.im_db_config.env
    working_dir: /app
    entrypoint: /app/devops/docker_build/entrypoint.sh
```

An alternative approach is to pass a `$GIT_ROOT_DIR` env var and refer to that

```
    volumes:
      - $GIT_ROOT_DIR:/app
      - ~/.aws:/app/home/.aws
    env_file:
      - $GIT_ROOT_DIR/env/local.im_db_config.env
    working_dir: /app
    entrypoint: /app/devops/docker_build/entrypoint.sh
```
